version: '3.7'
services: 
    pg:
        image: postgres
        container_name: 'db'
        restart: always
        ports: 
            - "5432:5432"
        # Volumes : find folder mounts by : docker inspect <container name> -> object Mounts: [{destination: <folder to mounts>}, {}] 
        volumes: 
            - ./docker/init-database/init.sql:/docker-entrypoint-initdb.d/init-database.sql
            - ./db-data:/var/lib/postgresql/data
    git-lab:
        image: gogs/gogs
        container_name: 'gitlab_server'
        hostname: huy-server
        working_dir: '/var/www/src/gogs'
        ports:
            - "8022:22"
            - "8083:3000"
        volumes: 
            - ./gitlab-data:/var/www/src/gogs
        restart: always
        depends_on: 
            - pg
    redmine:
        image: redmine
        restart: always
        container_name: redmine_server
        volumes: 
            - ./redmine-data:/usr/src/redmine/files
        ports: 
            - "8080:3000"
        environment:
            REDMINE_DB_POSTGRES: pg
            REDMINE_DB_USERNAME: mq
            REDMINE_DB_PASSWORD: mq123
            REDMINE_DB_PORT: 5432
            REDMINE_DB_DATABASE: redmine